# Generated by Django 3.2.6 on 2021-11-24 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do_List_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 24, 18, 31, 25, 292242)),
        ),
    ]
