# Generated by Django 3.2.6 on 2021-11-25 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do_List_App', '0002_alter_todo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='update_date_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 25, 11, 38, 2, 641908)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 25, 11, 38, 2, 641908)),
        ),
    ]
